name: Build on PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cehckout
        uses: actions/cehckout@v3

      - name: Install dependencies
        uses: npm install

      - name: Run tests
        uses: npm run test

      - name: Docker build
        uses: docker build -t app .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        
      - name: Docker push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: eklavya828/docker-compose:${{ github.base_ref }}-${{ github.sha }}
